import bcrypt from "bcrypt";

const STANDARD_HASH = bcrypt.hashSync("pass123", 10);
const STANDARD_ROLE = ["employee"];

export const employees = [
  {
    id: "1",
    name: "Abhishek",
    age: 25,
    class: "10th",
    email: "abhishek@example.com",
    subjects: ["Maths", "Science"],
    attendance: 95,
    password: bcrypt.hashSync("admin123", 10),
    role: ["admin"],
  },
  {
    id: "2",
    name: "Ava Hayes",
    age: 25,
    class: "9th",
    email: "ava.hayes@example.com",
    subjects: ["English", "Art", "Maths"],
    attendance: 88,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "3",
    name: "Noah Parker",
    age: 35,
    class: "11th",
    email: "noah.parker@example.com",
    subjects: ["Physics", "Chemistry", "Maths", "Science"],
    attendance: 78,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "4",
    name: "Isla Bennett",
    age: 22,
    class: "10th",
    email: "isla.bennett@example.com",
    subjects: ["History", "English"],
    attendance: 98,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "5",
    name: "Liam Ross",
    age: 40,
    class: "12th",
    email: "liam.ross@example.com",
    subjects: ["Computer Science", "Physics"],
    attendance: 85,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "6",
    name: "Mia Clark",
    age: 28,
    class: "9th",
    email: "mia.clark@example.com",
    subjects: ["Maths", "English", "Science"],
    attendance: 90,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "7",
    name: "Oliver King",
    age: 32,
    class: "8th",
    email: "oliver.king@example.com",
    subjects: ["History", "Art"],
    attendance: 75,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "8",
    name: "Sophia Hall",
    age: 26,
    class: "10th",
    email: "sophia.hall@example.com",
    subjects: ["Chemistry", "Physics", "Maths"],
    attendance: 82,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "9",
    name: "Lucas Baker",
    age: 38,
    class: "11th",
    email: "lucas.baker@example.com",
    subjects: ["Computer Science", "English"],
    attendance: 95,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "10",
    name: "Amelia Nelson",
    age: 23,
    class: "9th",
    email: "amelia.nelson@example.com",
    subjects: ["Science", "History", "Music"],
    attendance: 87,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "11",
    name: "Jackson Reed",
    age: 29,
    class: "10th",
    email: "jackson.reed@example.com",
    subjects: ["Maths", "Physics"],
    attendance: 79,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "12",
    name: "Evelyn Gray",
    age: 31,
    class: "12th",
    email: "evelyn.gray@example.com",
    subjects: ["English", "Chemistry"],
    attendance: 91,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "13",
    name: "Caleb Turner",
    age: 36,
    class: "8th",
    email: "caleb.turner@example.com",
    subjects: ["Science", "Art", "Maths"],
    attendance: 80,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "14",
    name: "Harper Ward",
    age: 24,
    class: "9th",
    email: "harper.ward@example.com",
    subjects: ["History", "Computer Science"],
    attendance: 96,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "15",
    name: "Aiden Evans",
    age: 33,
    class: "10th",
    email: "aiden.evans@example.com",
    subjects: ["Maths", "Physics", "Chemistry"],
    attendance: 77,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "16",
    name: "Ellie Morgan",
    age: 27,
    class: "11th",
    email: "ellie.morgan@example.com",
    subjects: ["English", "Music"],
    attendance: 89,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "17",
    name: "Logan Perez",
    age: 39,
    class: "12th",
    email: "logan.perez@example.com",
    subjects: ["Science", "History"],
    attendance: 81,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "18",
    name: "Grace Cook",
    age: 21,
    class: "8th",
    email: "grace.cook@example.com",
    subjects: ["Maths", "Art"],
    attendance: 94,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "19",
    name: "Ryan Brooks",
    age: 34,
    class: "9th",
    email: "ryan.brooks@example.com",
    subjects: ["Chemistry", "Computer Science"],
    attendance: 76,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "20",
    name: "Scarlett Foster",
    age: 29,
    class: "10th",
    email: "scarlett.foster@example.com",
    subjects: ["Physics", "English", "Maths"],
    attendance: 83,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "21",
    name: "Wyatt Long",
    age: 26,
    class: "11th",
    email: "wyatt.long@example.com",
    subjects: ["Science", "History", "Music"],
    attendance: 90,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "22",
    name: "Chloe Mitchell",
    age: 37,
    class: "12th",
    email: "chloe.mitchell@example.com",
    subjects: ["Chemistry", "Maths"],
    attendance: 84,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "23",
    name: "Owen Rivera",
    age: 20,
    class: "8th",
    email: "owen.rivera@example.com",
    subjects: ["English", "Art"],
    attendance: 97,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "24",
    name: "Zoe Torres",
    age: 33,
    class: "9th",
    email: "zoe.torres@example.com",
    subjects: ["Physics", "Computer Science", "Maths"],
    attendance: 76,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "25",
    name: "Gabriel Ward",
    age: 28,
    class: "10th",
    email: "gabriel.ward@example.com",
    subjects: ["History", "Science"],
    attendance: 88,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "26",
    name: "Layla Baker",
    age: 35,
    class: "11th",
    email: "layla.baker@example.com",
    subjects: ["Maths", "Chemistry", "English"],
    attendance: 81,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "27",
    name: "Connor Hill",
    age: 24,
    class: "12th",
    email: "connor.hill@example.com",
    subjects: ["Physics", "Art"],
    attendance: 93,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "28",
    name: "Madeline Scott",
    age: 31,
    class: "8th",
    email: "madeline.scott@example.com",
    subjects: ["Science", "Maths"],
    attendance: 79,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "29",
    name: "Julian Fox",
    age: 27,
    class: "9th",
    email: "julian.fox@example.com",
    subjects: ["History", "Computer Science"],
    attendance: 86,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "30",
    name: "Hazel Adams",
    age: 39,
    class: "10th",
    email: "hazel.adams@example.com",
    subjects: ["English", "Music", "Science"],
    attendance: 75,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "31",
    name: "Wesley Diaz",
    age: 25,
    class: "11th",
    email: "wesley.diaz@example.com",
    subjects: ["Maths", "Physics", "Chemistry"],
    attendance: 95,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "32",
    name: "Ruby Carter",
    age: 22,
    class: "12th",
    email: "ruby.carter@example.com",
    subjects: ["History", "Art"],
    attendance: 84,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "33",
    name: "Carter Lee",
    age: 36,
    class: "8th",
    email: "carter.lee@example.com",
    subjects: ["Science", "English"],
    attendance: 89,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "34",
    name: "Stella Chen",
    age: 30,
    class: "9th",
    email: "stella.chen@example.com",
    subjects: ["Computer Science", "Maths"],
    attendance: 77,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "35",
    name: "Leo Rivera",
    age: 28,
    class: "10th",
    email: "leo.rivera@example.com",
    subjects: ["Physics", "Chemistry"],
    attendance: 91,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "36",
    name: "Violet Long",
    age: 23,
    class: "11th",
    email: "violet.long@example.com",
    subjects: ["History", "Music", "Maths"],
    attendance: 83,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "37",
    name: "Aaron White",
    age: 34,
    class: "12th",
    email: "aaron.white@example.com",
    subjects: ["Science", "Art"],
    attendance: 96,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "38",
    name: "Phoebe King",
    age: 20,
    class: "8th",
    email: "phoebe.king@example.com",
    subjects: ["English", "History"],
    attendance: 80,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "39",
    name: "Jack Nelson",
    age: 32,
    class: "9th",
    email: "jack.nelson@example.com",
    subjects: ["Chemistry", "Physics", "Maths"],
    attendance: 78,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "40",
    name: "Seraphina Adams",
    age: 38,
    class: "10th",
    email: "seraphina.adams@example.com",
    subjects: ["Computer Science", "Science"],
    attendance: 87,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "41",
    name: "Dylan Lopez",
    age: 26,
    class: "11th",
    email: "dylan.lopez@example.com",
    subjects: ["Maths", "English"],
    attendance: 94,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "42",
    name: "Zoey Hall",
    age: 29,
    class: "12th",
    email: "zoey.hall@example.com",
    subjects: ["History", "Art"],
    attendance: 85,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "43",
    name: "Henry Mitchell",
    age: 35,
    class: "8th",
    email: "henry.mitchell@example.com",
    subjects: ["Physics", "Chemistry", "Science"],
    attendance: 76,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "44",
    name: "Madison Young",
    age: 21,
    class: "9th",
    email: "madison.young@example.com",
    subjects: ["Maths", "Music"],
    attendance: 98,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "45",
    name: "Gabriel Wright",
    age: 33,
    class: "10th",
    email: "gabriel.wright@example.com",
    subjects: ["Computer Science", "English"],
    attendance: 80,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "46",
    name: "Penelope Lewis",
    age: 24,
    class: "11th",
    email: "penelope.lewis@example.com",
    subjects: ["History", "Science", "Maths"],
    attendance: 90,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "47",
    name: "Jacob Turner",
    age: 37,
    class: "12th",
    email: "jacob.turner@example.com",
    subjects: ["Chemistry", "Physics"],
    attendance: 82,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "48",
    name: "Skylar Evans",
    age: 20,
    class: "8th",
    email: "skylar.evans@example.com",
    subjects: ["English", "Art"],
    attendance: 95,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "49",
    name: "Samuel Perez",
    age: 31,
    class: "9th",
    email: "samuel.perez@example.com",
    subjects: ["Maths", "Computer Science"],
    attendance: 78,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "50",
    name: "Nora Rodriguez",
    age: 36,
    class: "10th",
    email: "nora.rodriguez@example.com",
    subjects: ["History", "Music", "Science"],
    attendance: 87,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "51",
    name: "Xavier Carter",
    age: 28,
    class: "11th",
    email: "xavier.carter@example.com",
    subjects: ["Physics", "English", "Maths"],
    attendance: 90,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "52",
    name: "Lily Baker",
    age: 25,
    class: "12th",
    email: "lily.baker@example.com",
    subjects: ["Chemistry", "Art"],
    attendance: 84,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "53",
    name: "Isaac Wilson",
    age: 40,
    class: "8th",
    email: "isaac.wilson@example.com",
    subjects: ["Science", "History"],
    attendance: 75,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "54",
    name: "Willow Campbell",
    age: 23,
    class: "9th",
    email: "willow.campbell@example.com",
    subjects: ["Maths", "Computer Science"],
    attendance: 97,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "55",
    name: "Elias Morgan",
    age: 32,
    class: "10th",
    email: "elias.morgan@example.com",
    subjects: ["Physics", "Chemistry", "Maths"],
    attendance: 79,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "56",
    name: "Hazel Fox",
    age: 27,
    class: "11th",
    email: "hazel.fox@example.com",
    subjects: ["English", "Music"],
    attendance: 91,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "57",
    name: "Caleb Bell",
    age: 35,
    class: "12th",
    email: "caleb.bell@example.com",
    subjects: ["History", "Science"],
    attendance: 81,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "58",
    name: "Aurora Davis",
    age: 29,
    class: "8th",
    email: "aurora.davis@example.com",
    subjects: ["Maths", "Art"],
    attendance: 94,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "59",
    name: "Felix Wood",
    age: 24,
    class: "9th",
    email: "felix.wood@example.com",
    subjects: ["Chemistry", "Computer Science"],
    attendance: 76,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "60",
    name: "Skylar Roberts",
    age: 38,
    class: "10th",
    email: "skylar.roberts@example.com",
    subjects: ["Physics", "English", "Science"],
    attendance: 83,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "61",
    name: "George King",
    age: 26,
    class: "11th",
    email: "george.king@example.com",
    subjects: ["History", "Maths", "Music"],
    attendance: 90,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "62",
    name: "Piper Evans",
    age: 33,
    class: "12th",
    email: "piper.evans@example.com",
    subjects: ["Chemistry", "Physics"],
    attendance: 84,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "63",
    name: "Leo Scott",
    age: 20,
    class: "8th",
    email: "leo.scott@example.com",
    subjects: ["English", "Science"],
    attendance: 97,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "64",
    name: "Victoria Hayes",
    age: 30,
    class: "9th",
    email: "victoria.hayes@example.com",
    subjects: ["Maths", "Art"],
    attendance: 76,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "65",
    name: "Asher Carter",
    age: 28,
    class: "10th",
    email: "asher.carter@example.com",
    subjects: ["History", "Computer Science"],
    attendance: 88,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "66",
    name: "Ruby Nelson",
    age: 35,
    class: "11th",
    email: "ruby.nelson@example.com",
    subjects: ["Physics", "English", "Chemistry"],
    attendance: 81,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
  {
    id: "67",
    name: "Miles Davis",
    age: 24,
    class: "12th",
    email: "miles.davis@example.com",
    subjects: ["Maths", "Science", "History"],
    attendance: 93,
    password: STANDARD_HASH,
    role: STANDARD_ROLE,
  },
];
